### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by AGM7** [heximcz/routerboard-backup#9]
Hi!
I have tested version 1.0.0 and I have
[Http\Client\Exception\NetworkException]
  Error creating resource: [message] fopen(http://127.0.0.1/api/v4/proje
  cts?search=Mikrotikbackup): failed to open stream: Connection refused
  [file] /opt/routerboard-backup/vendor/guzzlehttp/guzzle/src/Handler/StreamH
  andler.php
  [line] 324

  [GuzzleHttp\Exception\ConnectException]
  Error creating resource: [message] fopen(http://127.0.0.1/api/v4/proje
  cts?search=Mikrotikbackup): failed to open stream: Connection refused
  [file] /opt/routerboard-backup/vendor/guzzlehttp/guzzle/src/Handler/StreamH
  andler.php
  [line] 324

  [RuntimeException]
  Error creating resource: [message] fopen(http://127.0.0.1/api/v4/proje
  cts?search=Mikrotikbackup): failed to open stream: Connection refused
  [file] /opt/routerboard-backup/vendor/guzzlehttp/guzzle/src/Handler/StreamH
  andler.php
  [line] 324

I try to backup to Gitlab(10.2.2)
What is an error?
Help me please

**Comment by heximcz** [comment]
Hi,
please check your configuration file:
```
gitlab:
    # gitlab api url - like this: http://git.your-domain.com/api/v4/
    url: 'https://<your-domain>/api/v4/'
    ....
    token: <!!! Personal Access Tokens !!!>
```
Private Token support has been removed in GitLab 10.2, from this version please use [Personal Access Tokens](https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html)
